  

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool: 
    vmImage: 'windows-latest' 
  steps:
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'
  - task: CmdLine@2
    inputs:
      script: |
        reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
        reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
        reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
        reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
  - task: VSTestV2WithXUnit@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**/*XUnitDataDrivenTestsProject*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)\XunitDataDrivenTestsProject\bin\Debug\net472'
      vsTestVersion: 'toolsInstaller'
